# Generated by Django 3.0.7 on 2022-11-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automater', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='excel',
        ),
    ]
