# Generated by Django 3.0.7 on 2022-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automater', '0004_delete_excel'),
    ]

    operations = [
        migrations.CreateModel(
            name='excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='')),
                ('added_date', models.DateField(auto_now_add=True, verbose_name='Upload Date')),
                ('added_time', models.TimeField(auto_now_add=True, verbose_name='Upload Time')),
            ],
        ),
    ]
